image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ""
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_HOST: tcp://localhost:2375



stages:
  - package
  - build
  - deploy



root-build:
  stage: package
  image: node:latest
  allow_failure: true
  script:
    - ls
    - npm install 
    - /bin/bash ./k8s/set-env.sh
    - npm run build
    - ls /root/.npm/
    - ls dist
    - sed -i 's/1890ff/51B5AA/g' dist/color.less    
  artifacts:
    paths:
      - ./dist
    expire_in: 5 mins
  only:
    refs:
    - develop    
    - master
    - develop_davis


services-build:
  stage: build
  before_script:
    - apk update && apk add bash && apk add git && apk add py-pip
    - pip install awscli
  script:
    - set -e
    - docker -v
    - aws ecr get-login
    - eval $(aws ecr get-login | sed 's/-e none//g')
    - ls
    - docker build -t "488938767527.dkr.ecr.us-east-2.amazonaws.com/veo-service:manhattan-frontend-${CI_COMMIT_SHA}" .
    - docker push "488938767527.dkr.ecr.us-east-2.amazonaws.com/veo-service:manhattan-frontend-${CI_COMMIT_SHA}"
  only:
    refs:
    - develop
    - master
    - develop_davis



services-deploy:
  stage: deploy
  cache:
    paths:
      - /usr/local/bin/kubectl
  script:
     - apk update && apk add bash && apk add git
     - set -e
     - /bin/bash ./k8s/kube_deploy.sh
  only:
    refs:
    - develop
    - master
    - develop_davis