image: docker:19.03.0
services:
  - docker:19.03.0-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - package
  - build
  - deploy

root-build:
  stage: package
  image: node:latest
  script:
    - /bin/bash ./k8s/package.sh
  artifacts:
    paths:
      - ./dist
    expire_in: 10 mins
  only:
    refs:
    - develop    
    - master


services-build:
  stage: build
  before_script:
    - apk update && apk add bash && apk add git && apk add py-pip
    - pip install awscli
  script:
    - /bin/bash ./k8s/build.sh
  only:
    refs:
    - develop
    - master



services-deploy:
  stage: deploy
  script:
     - /bin/bash ./k8s/deploy.sh
  only:
    refs:
    - develop
    - master